# Workflow name
name: Backend Continuous Integration

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main

# Jobs defined in the workflow
jobs:
  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-python@v5
    with:
      python-version: '3.13'
      cache: 'pip'
  - run: python -m pip install -r requirements.txt
  lint:
    # The operating system for the runner
    runs-on: ubuntu-latest

    # Steps in the job
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Python
        uses: actions/setup-python@v3
        with:
          pyt-version: latest
          cache: 'pip'

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Run lint
        run: pipenv run lint

      - name: Print a message
        run: echo "Lint job completed"

  test:
    # The operating system for the runner
    runs-on: ubuntu-latest

    # Steps in the job
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Python
        uses: actions/setup-python@v3
        with:
          pyt-version: latest
          cache: 'pip'

      - name: Install pipenv
        run: pip install pipenv

      - name: Run tests
        run: pipenv run test

      - name: Print a message
        run: echo "Test job completed"

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to container registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: <your-container-registry>/<your-image>:latest
